global:
  scrape_interval: 15s # How often the metrics are yielded

scrape_configs:
  # Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Server metrics (CPU, RAM, Disk)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker containers metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Web app metrics
  - job_name: 'web-app'
    static_configs:
      - targets: ['web:5000']