apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: nuclear-analytics
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ssomkk/web-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DATA_DIR
              value: /app/data/raw
            - name: REPORTS_DIR
              value: /app/reports/lab1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
