apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: nuclear-analytics
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
